In [1]:
import numpy as np 
import pandas as pd 
inputdata = pd.read_csv('NYC_Crime_Cleaned.csv')

In [2]:
target = inputdata["Offence_Type"].unique()

In [3]:
data_dict = {}
count = 1
for data in target:
    data_dict[data] = count
    count = count + 1
inputdata["Offence_Type"] = inputdata["Offence_Type"].replace(data_dict)

In [4]:
inputdata['Start_Date'] = pd.to_datetime(inputdata['Start_Date'])

In [5]:
inputdata['day_of_week'] = inputdata['Start_Date'].dt.day_name()

In [6]:
inputdata['day_of_week'].unique()

array(['Sunday', 'Saturday', 'Friday', 'Thursday', 'Wednesday', 'Tuesday',
       'Monday'], dtype=object)

In [7]:
district = inputdata["Offence_Level"].unique()
data_dict_district = {}
count = 1
for data in district:
    data_dict_district[data] = count
    count+=1
inputdata["Offence_Level"] = inputdata["Offence_Level"].replace(data_dict_district).dropna()

In [8]:
inputdata

,Complaint_ID,Start_Date,Start_Time,Neighborhood,Offence_Code,Offence_Type,Status,Offence_Level,Borough,Latitude,Longitude,Lat_Lon,day_of_week
0,849484321,2011-11-27 00:00:00+00:00,00:02:00,14.0,347,1,COMPLETED,1,MANHATTAN,40.743889,-73.981560,"(40.743889053, -73.981560335)",Sunday
1,201779846,2011-11-27 00:00:00+00:00,00:01:00,113.0,106,2,COMPLETED,2,QUEENS,40.688664,-73.775754,"(40.688664293, -73.775754035)",Sunday
2,528511042,2011-11-27 00:00:00+00:00,00:01:00,10.0,110,3,COMPLETED,2,MANHATTAN,40.741818,-74.008471,"(40.74181793, -74.008471105)",Sunday
3,741313529,2011-11-27 00:00:00+00:00,00:01:00,70.0,126,4,COMPLETED,2,BROOKLYN,40.648159,-73.958206,"(40.648159153, -73.958206302)",Sunday
4,517952221,2011-11-27 00:00:00+00:00,00:00:00,23.0,344,5,COMPLETED,1,MANHATTAN,40.796790,-73.939404,"(40.796790443, -73.939404406)",Sunday
5,888361194,2011-11-27 00:00:00+00:00,00:00:00,88.0,351,6,COMPLETED,1,BROOKLYN,40.690887,-73.978788,"(40.690887248, -73.978787583)",Sunday
6,211551597,2011-11-27 00:00:00+00:00,00:00:00,100.0,121,6,COMPLETED,2,QUEENS,40.592676,-73.799218,"(40.592675544, -73.799217868)",Sunday
7,482588995,2011-11-27 00:00:00+00:00,00:00:00,18.0,341,7,COMPLETED,1,MANHATTAN,40.765291,-73.993211,"(40.765291116, -73.993211061)",Sunday
8,997922834,2011-11-26 00:00:00+00:00,23:59:00,94.0,109,8,COMPLETED,2,BROOKLYN,40.729720,-73.951163,"(40.72971999, -73.951162729)",Saturday
9,220891615,2011-11-26 00:00:00+00:00,23:58:00,43.0,235,9,COMPLETED,1,BRONX,40.836566,-73.871348,"(40.836565997, -73.871348148)",Saturday
10,331893950,2011-11-26 00:00:00+00:00,23:58:00,115.0,344,5,COMPLETED,1,QUEENS,40.755910,-73.882116,"(40.75590985, -73.882115805)",Saturday
11,367835683,2011-11-26 00:00:00+00:00,23:55:00,73.0,105,10,COMPLETED,2,BROOKLYN,40.682666,-73.910026,"(40.682666375, -73.910025795)",Saturday
12,616879973,2011-11-26 00:00:00+00:00,23:55:00,120.0,344,5,COMPLETED,1,STATEN ISLAND,40.623849,-74.081980,"(40.623848889, -74.081979859)",Saturday
13,587598699,2011-11-26 00:00:00+00:00,23:50:00,42.0,106,2,COMPLETED,2,BRONX,40.830313,-73.898711,"(40.830313367, -73.898710964)",Saturday
14,262364691,2011-11-26 00:00:00+00:00,23:50:00,42.0,106,2,COMPLETED,2,BRONX,40.830313,-73.898711,"(40.830313367, -73.898710964)",Saturday
15,158917420,2011-11-26 00:00:00+00:00,23:50:00,42.0,106,2,COMPLETED,2,BRONX,40.830313,-73.898711,"(40.830313367, -73.898710964)",Saturday
16,627711444,2011-11-20 00:00:00+00:00,17:28:00,44.0,341,7,COMPLETED,1,BRONX,40.837324,-73.919831,"(40.837323511, -73.919830757)",Sunday
17,510463237,2011-11-26 00:00:00+00:00,23:50:00,42.0,106,2,COMPLETED,2,BRONX,40.830313,-73.898711,"(40.830313367, -73.898710964)",Saturday
18,325590321,2011-11-26 00:00:00+00:00,23:50:00,42.0,106,2,COMPLETED,2,BRONX,40.830313,-73.898711,"(40.830313367, -73.898710964)",Saturday
19,840831794,2011-11-26 00:00:00+00:00,23:50:00,42.0,106,2,COMPLETED,2,BRONX,40.830313,-73.898711,"(40.830313367, -73.898710964)",Saturday
20,691277763,2011-11-26 00:00:00+00:00,23:50:00,76.0,344,5,COMPLETED,1,BROOKLYN,40.676331,-74.008683,"(40.676330602, -74.008682701)",Saturday
21,565042303,2011-11-26 00:00:00+00:00,23:50:00,83.0,347,1,COMPLETED,1,BROOKLYN,40.695349,-73.905779,"(40.695349313, -73.905778604)",Saturday
22,238812144,2011-11-26 00:00:00+00:00,23:50:00,105.0,351,6,COMPLETED,1,QUEENS,40.729097,-73.713787,"(40.729097426, -73.713786943)",Saturday
23,967204946,2011-11-26 00:00:00+00:00,23:50:00,122.0,578,11,COMPLETED,3,STATEN ISLAND,40.600401,-74.163627,"(40.600400686, -74.163627084)",Saturday
24,955238299,2011-11-26 00:00:00+00:00,23:47:00,52.0,106,2,COMPLETED,2,BRONX,40.876028,-73.875022,"(40.876027906, -73.87502159)",Saturday
25,358168582,2011-11-26 00:00:00+00:00,23:45:00,40.0,235,9,COMPLETED,1,BRONX,40.808798,-73.916184,"(40.808797805, -73.916184132)",Saturday
26,119316651,2011-11-26 00:00:00+00:00,23:45:00,46.0,126,4,COMPLETED,2,BRONX,40.851327,-73.908413,"(40.851326749, -73.908413245)",Saturday
27,457933985,2011-11-26 00:00:00+00:00,23:45:00,46.0,359,12,COMPLETED,1,BRONX,40.851327,-73.908413,"(40.851326749, -73.908413245)",Saturday
28,589023478,2011-11-26 00:00:00+00:00,23:45:00,115.0,110,3,COMPLETED,2,QUEENS,40.767457,-73.881734,"(40.767456606, -73.881734355)",Saturday
29,774755690,2011-11-26 00:00:00+00:00,23:44:00,48.0,351,6,COMPLETED,1,BRONX,40.842521,-73.880773,"(40.842521172, -73.880773262)",Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6017023,169058890,2011-11-27 00:00:00+00:00,00:35:00,43.0,351,6,COMPLETED,1,BRONX,40.818769,-73.850529,"(40.818768839, -73.850528931)",Sunday
6017024,330114043,2011-11-27 00:00:00+00:00,00:30:00,42.0,361,16,COMPLETED,1,BRONX,40.824774,-73.908211,"(40.824774247, -73.908211317)",Sunday
6017025,577109494,2011-11-27 00:00:00+00:00,00:30:00,44.0,121,6,COMPLETED,2,BRONX,40.837163,-73.917851,"(40.837162925, -73.917850539)",Sunday
6017026,342445130,2011-11-27 00:00:00+00:00,00:30:00,60.0,126,4,COMPLETED,2,BROOKLYN,40.577208,-73.990289,"(40.577207916, -73.990289118)",Sunday
6017027,153850866,2011-11-27 00:00:00+00:00,00:30:00,66.0,353,22,COMPLETED,1,BROOKLYN,40.640530,-73.984608,"(40.640529724, -73.984608407)",Sunday
6017028,571495358,2011-11-27 00:00:00+00:00,00:30:00,71.0,106,2,COMPLETED,2,BROOKLYN,40.666133,-73.931384,"(40.666132836, -73.93138386)",Sunday
6017029,774780387,2011-11-27 00:00:00+00:00,00:30:00,79.0,341,7,COMPLETED,1,BROOKLYN,40.680003,-73.942236,"(40.680002664, -73.942236182)",Sunday
6017030,479354226,2011-11-27 00:00:00+00:00,00:30:00,7.0,351,6,COMPLETED,1,MANHATTAN,40.712814,-73.988076,"(40.712813778, -73.988076222)",Sunday
6017031,792070006,2011-11-27 00:00:00+00:00,00:30:00,70.0,341,7,COMPLETED,1,BROOKLYN,40.628185,-73.956331,"(40.628184639, -73.956331062)",Sunday
6017032,546300062,2011-11-27 00:00:00+00:00,00:30:00,90.0,344,5,COMPLETED,1,BROOKLYN,40.710441,-73.968523,"(40.710441363, -73.968523003)",Sunday
6017033,591439063,2011-11-27 00:00:00+00:00,00:30:00,43.0,341,7,COMPLETED,1,BRONX,40.816366,-73.867626,"(40.816366145, -73.867626311)",Sunday
6017034,158680970,2011-11-27 00:00:00+00:00,00:27:00,40.0,359,12,COMPLETED,1,BRONX,40.818414,-73.907277,"(40.818413984, -73.907277131)",Sunday
6017035,768297553,2011-11-27 00:00:00+00:00,00:25:00,33.0,348,23,COMPLETED,1,MANHATTAN,40.837189,-73.942602,"(40.837188876, -73.942602044)",Sunday
6017036,963981477,2011-11-27 00:00:00+00:00,00:21:00,1.0,340,26,COMPLETED,1,MANHATTAN,40.726063,-74.005720,"(40.726063209, -74.005719911)",Sunday
6017037,314028272,2011-11-27 00:00:00+00:00,00:21:00,1.0,340,26,COMPLETED,1,MANHATTAN,40.726063,-74.005720,"(40.726063209, -74.005719911)",Sunday
6017038,665529587,2011-11-27 00:00:00+00:00,00:20:00,60.0,344,5,COMPLETED,1,BROOKLYN,40.576694,-73.984245,"(40.576693967, -73.984245136)",Sunday
6017039,528116203,2011-11-27 00:00:00+00:00,00:20:00,60.0,359,12,COMPLETED,1,BROOKLYN,40.576752,-73.983712,"(40.576751534, -73.983712353)",Sunday
6017040,979846689,2011-11-27 00:00:00+00:00,00:20:00,67.0,344,5,COMPLETED,1,BROOKLYN,40.662518,-73.927012,"(40.662518015, -73.927011804)",Sunday
6017041,231086927,2011-11-27 00:00:00+00:00,00:18:00,26.0,106,2,COMPLETED,2,MANHATTAN,40.814865,-73.960204,"(40.814865282, -73.960204199)",Sunday
6017042,750153027,2011-11-27 00:00:00+00:00,00:15:00,41.0,348,23,COMPLETED,1,BRONX,40.817886,-73.893325,"(40.817885913, -73.893325064)",Sunday
6017043,384645813,2011-11-27 00:00:00+00:00,00:15:00,106.0,105,10,COMPLETED,2,QUEENS,40.675834,-73.817271,"(40.675834499, -73.817270885)",Sunday
6017044,617951326,2011-11-27 00:00:00+00:00,00:10:00,40.0,235,9,COMPLETED,1,BRONX,40.817975,-73.918900,"(40.817975355, -73.918900273)",Sunday
6017045,921081248,2011-11-27 00:00:00+00:00,00:10:00,46.0,235,9,COMPLETED,1,BRONX,40.860585,-73.902548,"(40.860585317, -73.902547546)",Sunday
6017046,189280973,2011-11-27 00:00:00+00:00,00:10:00,61.0,126,4,COMPLETED,2,BROOKLYN,40.595159,-73.937981,"(40.595159063, -73.937981424)",Sunday
6017047,262751492,2011-11-27 00:00:00+00:00,00:10:00,113.0,118,13,COMPLETED,2,QUEENS,40.684851,-73.792804,"(40.684850817, -73.792803529)",Sunday
6017048,936341406,2011-11-27 00:00:00+00:00,00:05:00,46.0,344,5,COMPLETED,1,BRONX,40.861779,-73.898674,"(40.861778671, -73.898673888)",Sunday
6017049,461970235,2011-11-27 00:00:00+00:00,00:05:00,103.0,341,7,COMPLETED,1,QUEENS,40.712564,-73.753468,"(40.712564146, -73.753468042)",Sunday
6017050,319080219,2011-11-27 00:00:00+00:00,00:05:00,122.0,235,9,COMPLETED,1,STATEN ISLAND,40.581803,-74.109534,"(40.581803062, -74.1095336)",Sunday
6017051,736582694,2011-11-27 00:00:00+00:00,00:05:00,14.0,106,2,COMPLETED,2,MANHATTAN,40.756555,-73.992147,"(40.756554529, -73.992147146)",Sunday
6017052,643733947,2011-11-27 00:00:00+00:00,00:05:00,14.0,344,5,COMPLETED,1,MANHATTAN,40.756555,-73.992147,"(40.756554529, -73.992147146)",Sunday

In [9]:
inputdata = inputdata[['day_of_week','Latitude','Longitude','Offence_Level','Neighborhood','Borough']]

In [10]:
days = {'Monday':0,'Tuesday':1,'Wednesday':2,'Thursday':3,'Friday':4,'Saturday':5,'Sunday':6}
inputdata['day_of_week'] = inputdata['day_of_week'].apply(lambda x: days[x])

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [11]:
inputdata = inputdata.dropna()

In [12]:
cat = ['day_of_week','Borough']
dummie = pd.get_dummies(inputdata[cat])

In [13]:
inputdata = pd.concat([dummie,inputdata[['Latitude','Longitude','Offence_Level','Neighborhood']]],axis = 1)

In [14]:
from sklearn import linear_model, neighbors, preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
dummie_maxmin = min_max_scaler.fit_transform(inputdata.drop('Offence_Level',axis=1))

/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:334: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

In [15]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV, train_test_split, cross_val_score
X_train,X_test, y_train, y_test = train_test_split(inputdata.drop('Offence_Level',axis=1),inputdata['Offence_Level'],test_size=0.3,random_state=1)

In [16]:
X_train = X_train.values
X_test = X_test.values 
y_train = y_train.values
y_test = y_test.values

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 30)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)
predictions

array([1, 1, 1, ..., 2, 1, 1])

In [20]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,predictions)

0.5590719119142067

In [21]:
cm = confusion_matrix(predictions,y_test)
cm

array([[930265, 475748, 200106],
       [ 90133,  72412,  21366],
       [  3464,   1600,   2063]])

In [25]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100,random_state=0,criterion='gini',class_weight='balanced')
clf.fit(X_train,y_train)
y_predict = clf.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_predict)

0.4181326394967162

In [27]:
cm = confusion_matrix(y_predict,y_test)
cm

array([[453069, 200116,  71561],
       [295154, 205867,  59460],
       [275639, 143777,  92514]])